name: bus_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: 4.0.0
  latlong2: ^0.8.1
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/fundo0.jpg
    - assets/fundo1.jpg
    - assets/icon.png
    - assets/map_placeholder.png
    - assets/tela-load.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#836FFF"
  adaptive_icon_foreground: "assets/icon.png"
